### ISSUE TITLE
Change to notification email footer

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1016]
Hi,

Just noticed now that two small changes need to be made to the notificiation email footer. First sentence should say:

Trommons is maintained by The Rosetta Foundation, a non-profit organisation promoting equal access to information and knowledge across the languages of the world.

**Comment by Paulina-Rosetta** [comment]
It took me a few months to notice... there's a typo in the footer: 

Trommons is maintained by The Rosetta Foundation, a non-profit organisation promoting equal access to information and knowledge across the languageS of the world.

Is this easy to fix?

**Comment by Wasala** [comment]
Need to recompile the backend after doing this small change. So can we wait till the next update?

**Comment by Paulina-Rosetta** [comment]
Sure, no problem :-)

**Comment by Paulina-Rosetta** [comment]
Another two changes proposed by Marta:

-'Support Trommons' currently links to: http://www.therosettafoundation.org/participate/becomeafriend/
Change this to http://www.therosettafoundation.org/donate/

-Add at the end: "If you no longer wish to receive tasks steam notification emails, please visit your Profile page to edit your email notification settings."

**Comment by Wasala** [comment]
Implemented.
