### ISSUE TITLE
Alert message on Edit Profile page in English

### ISSUE THREAD

**Issue by aquascene** [TheRosettaFoundation/SOLAS-Match#1030]
When a user sets their language preference to Spanish, logs out and back in (so Spanish can take effect), and then changes their language preference back to English, the alert message that is displayed is in English where it should be in Spanish.

**Comment by Wasala** [comment]
@alanbarrett Can we mark this as resolved too?

**Comment by alanbarrett** [comment]
I think this will be OK with new code (although I am not 100% sure I understand), but I am marking as closed anyway as it is almost certainly fixed.
