### ISSUE TITLE
http://trommons.org/register/ link not working

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1043]
Volunteer can't register - see below

Thanks for your reply. The error message I have received is below. This appeared when I clicked on the 'register as a volunteer link under the 'volunteer as a translator/proofreader' heading in the  'participate' section of your website: http://trommons.org/register/  I'm using Google Chrome browser (version 38.0.2125.59) and currently accessing it from my iPad using the iOS8 operating system, but this also happened when trying to access it from my laptop which runs on Windows 7 (also using Google Chrome browser).
![image1](https://cloud.githubusercontent.com/assets/4759025/4767595/bf5267cc-5b5f-11e4-8b58-b8d366e98505.PNG)

**Comment by Wasala** [comment]
Closing the issue as no more comments received regarding this issue.
