### ISSUE TITLE
Reset password email not working

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1091]
Hi guys,

User http://trommons.org/7391/profile/ contacted me several times to say that she cannot access her account and her reset password email is not working. 

She got this email: 

calleruizisabel,
You have requested a password reset for your Trommons account. You can reset your password by copying the link below and pasting it into the address bar of your web browser. If you did not request a password please ignore this email.
http://trommons.org/7391/password/reset
Sincerely,
The Trommons Team

When she clicked on the link, she got this:

Warning! Incorrect Unique ID. Are you sure you copied the URL correctly?

Any idea?

Thanks

**Comment by aquascene** [comment]
Done :smiley:
