### ISSUE TITLE
Download a documents

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1105]
I can't download the documents of these projects: 

http://trommons.org/project/2584/view/

http://trommons.org/project/2585/view/

It appears: Warning! We could not find the requested file on our system. Requested file type: original task file. Please contact us at info@trommons.org with details of this problem.

Could you send me the document so that I'll be able to work in the segmentation?

Thanks!

**Comment by aquascene** [comment]
Project 2585 (http://trommons.org/project/2585/view/) is now fixed and can be downloaded from the task claim page.  Working on the other one now.

**Comment by aquascene** [comment]
For Project 2584 (http://trommons.org/project/2584/view/), there is no record of the file at all on either the database or the file system.  If you can get me the file for this project from the Org I can fix this one.

**Comment by AlbaPi** [comment]
I've sent you the document of Project 2584.

Thanks!

**Comment by aquascene** [comment]
Done :smiley:
