### ISSUE TITLE
Can't update native language on Chrome

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1106]
Bad news. Since you can'yt update your profile on Firefox I'm advising everyone to use Chrome. It turns out that when you set your native language on Chrome, it doesn't save.

**Comment by Paulina-Rosetta** [comment]
Specifically, I tried to update this user's naative language to Korean: http://trommons.org/7547/profile
I tried to see if anything else would save and the 'x's that I put in to test saved fine but now I can't delete them

**Comment by Wasala** [comment]
Working on this now..

**Comment by Wasala** [comment]
Fixed via f7ff1f862dbe943241a7053ef9d494b7fb193df3.
