### ISSUE TITLE
OpenID 2.0 Shutdown by Google and Implementing OpenID Connect

### ISSUE THREAD

**Issue by Wasala** [TheRosettaFoundation/SOLAS-Match#1119]
Google is retiring their OpenID 2.0 platform and users are getting a warning  saying "OpenID 2.0 for Google Accounts is going away" when trying to login to Trommons using the Google accounts (during the first time they authenticate their account). 

Google will shutdown OpenID 2.0 on April 20, 2015. Therefore necessary steps need to be taken immediately to migrate to Google+ Sign-In or OpenID Connect .

More info: https://developers.google.com/accounts/docs/OpenID#shutdown-timetable 

@spaceindaver How will this affect Trommons and any hints on where to begin?

**Comment by spaceindaver** [comment]
Hey, I don't really remember the code for the Google OpenID stuff but it should be pretty easy to implement. You add a new button (remember to remove the Google option from the openID list) which says "Sign in with Google+" and add the required javascript to send the request and a callback URL that will direct the user to the Solas API. This is exactly how the current OpenID implementation works. As for what to do at the callback I'm not too sure but it looks like all the documentation you need to get it working is linked in the URL you referenced above. I would imagine the Google servers will send some data to the server with info on the user (you will request this data with the javascript stuff that registered the callback and the user will be able to review and accept it before signing in). You can then use that info to determine if the user signed in to Google correctly and get their email address. With their email address you can find them in our database and call out login stuff the same way OpenID currently does. You might have to write some custom API functions for this but it might be able to work off the existing OpenID login functionality (I really can't remember how bespoke that API function is or how exactly we trigger the login once we know the user is authenticated but it should be easy enough to figure it out from the existing code).

**Comment by Wasala** [comment]
@spaceindaver Thank you very much for the detailed explanation! Will look into this soon, as more than half of the users in Trommons are likely to be affected by this..

**Comment by SeanMooney** [comment]
as a work around all google openid user can set a passward by using the password reset option and then sign in with email and password. im looking at  your stackoverflow question now.

**Comment by Wasala** [comment]
Implemented :)
