### ISSUE TITLE
More files in a segmentation

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1120]
Could you let us upload 50 files in this segmentation. Here is the link: http://trommons.org/task/6555/view/

**Comment by aquascene** [comment]
The system is designed to only allow a maximum of 10 segments.  We did this once before and I remember it took a long time to implement but resulted in live site issues on that project later down the line.  An alternative solution would be for the Org to segment the document themselves and uploading separate projects.

**Comment by AlbaPi** [comment]
Ok! Don't worry I thought that it was easy, I'll create 5 different projects. 
Thanks!
