### ISSUE TITLE
Can't download source file

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1121]
I'm getting this error message for the following project http://trommons.org/project/2672/view/

Warning! We could not find the requested file on our system. Requested file type: original task file. Please contact us at info@trommons.org with details of this problem.

We've emailed the NGO - any idea what went wrong here?

**Comment by Wasala** [comment]
The task folder (6744) was missing in the file system so I have created and copied the original source file into the task folder.

**Comment by Paulina-Rosetta** [comment]
I still can't seem to open the file?

**Comment by aquascene** [comment]
Done :smiley:

**Comment by Paulina-Rosetta** [comment]
Same problem here I think: http://trommons.org/task/6729/view/

**Comment by Wasala** [comment]
Task folder was missing again and no records founds in the task file versions. Fixed.
