### ISSUE TITLE
Desegmentation task claim button doesn't appear

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1123]
There is no Claim Task button on this desegmentation task : http://trommons.org/task/5682/view/
We have tried on both Firefox and Chrome. Any advice?

**Comment by TheIceMageX50** [comment]
I notice that the task status here is listed as "Waiting". I think that could mean either something is slightly wrong with the task on the system, or that for some reason the organisation has set some other task as a prerequisite of this task. If it's the latter, then it's analogous to the situation in the default workflow projects tend to follow (which I'm sure you're familiar with) where a Proofreading task tends to be "Waiting" for a Translation task to finish.

@Wasala or @aquascene shall have to have a look on the system to see how it looks. :)

**Comment by Wasala** [comment]
There are no tasks with this task set to as prerequisites. So not sure what went wrong here. Need to investigate de-segmentation tasks in dev environment.
 I have changed the status to pending claim and now the button is there!
