### ISSUE TITLE
Problem to access Trommons

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1134]
A volunteer emailed us with that email... 

Hello,
When I'm trying to connect to the site, both with Firefox and Chrome, I got
this message:

XML: not well-formed Indirizzo: http://trommons.org/ Line number 77, column
36:

<option template repeat="{{key in taskTypeIndexes}}"
value="{{key.toString()}}">
What should I do?

**Comment by Wasala** [comment]
@AlbaPi How may users have reported this issue so far?

Can we get the following info from the user:

* Versions of browsers
* Whether they have blocked Javascript in their browsers or not : http://enable-javascript.com/ 
* The language that they are trying to access trommons

Until you get that info, my only recommendation for the user is to do this: http://trommons.org/static/faq/#vol_q_trommons_not_working

**Comment by Wasala** [comment]
I am closing this as the above issue seems to have been resolved (or it will be resolved with new javascripts)
