### ISSUE TITLE
Wrong error message when adding organisation member

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1135]
When an org tries to add a user as a member who hasn't got a user account, they get the following error: X is already a member of this organisation. 

![error](https://cloud.githubusercontent.com/assets/4759025/6801775/d5a1adf0-d222-11e4-9c38-11a195d8bc4b.png)

**Comment by Wasala** [comment]
Duplication of #1078
