### ISSUE TITLE
Wrong translation uploaded

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1146]
We need to upload a new file for this task - the volunteer uploaded the English original by mistake: http://trommons.org/task/6669/view/

The proofreader unfortunately re-uploaded the original also, so we need to 'reset' the associated proofreading task to 'unclaimed'.

**Comment by Wasala** [comment]
Task 6669 -  volunteer can re-upload the file now.
Task 6670 -  reverted to uncliamed status.
