### ISSUE TITLE
Change the words

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1151]
Could you change the words of these tasks that have already been claimed?

http://trommons.org/task/7695/view/ = 6160 words
http://trommons.org/task/7697/view/ = 4411 words
http://trommons.org/task/7699/view/ = 6388 words
http://trommons.org/task/7707/view/ = 6606 words

Thanks! :)

**Comment by Wasala** [comment]
Done :)
