### ISSUE TITLE
File uploaded in the wrong language

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1154]
We've had 2 instances of this over the weekend... Volunteers have claimed a task, translated it into the wrong target language and uploaded it. So the tasks need to be 'reset':

http://trommons.org/task/5073/view
http://trommons.org/task/1977/view

**Comment by Wasala** [comment]
Working on these now.

**Comment by Wasala** [comment]
Done!
