### ISSUE TITLE
User 8616 can't access the site

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1155]
Here's her profile: http://trommons.org/8616/profile/
And message: It seems that my account hasn´t been verified yet so I cannot actually log in. That was happening on last Tuesday the 28th and is still happening today (and in the mean time I´ve been messing up the whole thing trying to reset my password so now I´m not sure which is my password either)

Can you help?

**Comment by Wasala** [comment]
I have manually verified the user, so she should be able to login now using the last password that she used.
