### ISSUE TITLE
Download a document

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1171]
http://trommons.org/org/208/task/7101/complete

Could you get me that document? When I am trying to download the file, it appears me: "Warning! We could not find the requested file on our system. Requested file type: latest task file version. Please contact us at info@trommons.org with details of this problem."

I've emailed the volunteer and I got a Mail Returned so if you could retrieve the file, it would be great! 

Thanks!

**Comment by Wasala** [comment]
Sent info via email.
