### ISSUE TITLE
Problem to access Trommons

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1175]
This volunteer Anna Perucho-Outarahout <anna.perucho@sfr.fr> can't access on Trommos. She has tried to reset the password, but she is not receiving any email. What should I tell her?

**Comment by Wasala** [comment]
I tried in the backend's current output log and nothing was found for this user. This user is a verified user. I will have to restart the backend and the mail-server in this case and try to reset her password.

**Comment by Wasala** [comment]
The user should definitely get the password reset email now. I am emailing it to you too.
