### ISSUE TITLE
List All Badges button not working

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1176]
When clicking the List All Badges button the the Profile page (http://trommons.org/badge/list/), I receive the following error message:

You can report this problem by E-Mailing us at info@trommons.org
with details of how you encountered the error, along with the technical details listed below. 

Slim Application Error

Message:DOMXPath::query(): Invalid predicate
Loc: /repo/solas-match/ui/lib/Localisation.php
Line: 90
Code: 2

Trace:

0 [internal function]: Slim\Slim::handleErrors(2, 'DOMXPath::query...', '/repo/solas-mat...', 90, Array)
1 /repo/solas-match/ui/lib/Localisation.php(90): DOMXPath->query('/resources/stri...')
2 /repo/solas-match/ui/templating/templates_compiled/92a1ab6e9d5404f1bd7e388a1f4d76207cbf098c.file.badge-list.tpl.php(66): SolasMatch\UI\Lib\Localisation::getTranslation('Association rec...')
3 /repo/solas-match/ui/vendor/smarty/smarty/distribution/libs/sysplugins/smarty_internal_templatebase.php(182): content_554bc20208a436_37010128(Object(Smarty_Internal_Template))
4 /repo/solas-match/ui/vendor/slim/views/Slim/Views/Smarty.php(90): Smarty_Internal_TemplateBase->fetch('badge/badge-lis...', NULL)
5 /repo/solas-match/ui/vendor/slim/slim/Slim/View.php(255): Slim\Views\Smarty->render('badge/badge-lis...', NULL)
6 /repo/solas-match/ui/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('badge/badge-lis...', NULL)
7 /repo/solas-match/ui/vendor/slim/slim/Slim/Slim.php(751): Slim\View->display('badge/badge-lis...')
8 /repo/solas-match/ui/RouteHandlers/BadgeRouteHandler.class.php(47): Slim\Slim->render('badge/badge-lis...')
9 [internal function]: SolasMatch\UI\RouteHandlers\BadgeRouteHandler->badgeList()
10 /repo/solas-match/ui/vendor/slim/slim/Slim/Route.php(441): call_user_func_array(Array, Array)
11 /repo/solas-match/ui/vendor/slim/slim/Slim/Slim.php(1314): Slim\Route->dispatch()
12 /repo/solas-match/ui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
13 /repo/solas-match/ui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
14 /repo/solas-match/ui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
15 /repo/solas-match/ui/vendor/slim/slim/Slim/Slim.php(1261): Slim\Middleware\SessionCookie->call()
16 /repo/solas-match/index.php(191): Slim\Slim->run()
17 {main}

**Comment by alanbarrett** [comment]
The following badge from the database (using call getBadge(null,null,null,null); )...
| 100 |       28 | Les petits frÃ¨res des Pauvres             | Association reconnue d''utilitÃ© publique venant en aide aux personnes Ã¢gÃ©es de plus de 50 ans vivant isolÃ©es, vivant dans des conditions de prÃ©caritÃ© multiples.    

... does not have a translation so Localisation::getTranslation($badgeEntry->getDescription()) fails. I do not know what is supposed to happen?

I have to leave for Liverpool now!

    Alan.

**Comment by Wasala** [comment]
I will look into this.

**Comment by Wasala** [comment]
Fixed in develop.

**Comment by Wasala** [comment]
Fixed
