### ISSUE TITLE
About Recently Viewed Tasks 

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1179]
In the Recently Viewed Tasks section I am able to see tasks that are already in progress. Can the volunteers see them, as well? It is a little bit confusing…

**Comment by Paulina-Rosetta** [comment]
Also, the list is a bit too 'busy' IMO. I think we should add an extra space between the tasks
![recently viewed tasks](https://cloud.githubusercontent.com/assets/4759025/7795815/4aa4dfb8-02d0-11e5-8d6e-e726e2ba6bd2.png)

**Comment by Wasala** [comment]
@AlbaPi Yes, I did this intentionally so that this can be especially useful for you to monitor tasks that you are dealing with.  But I can easily restrict this only to unclaimed tasks if you'd like. Please let me know.

**Comment by Wasala** [comment]
@Paulina-Rosetta  try clearing cache in your browser?  Can you check with a different browser too?
because I had implemented a shading background for each task, which does not seem to be there in your screen-shot. If you still think it is too busy even with the shading, I can increase the gap. please let me know.

**Comment by Paulina-Rosetta** [comment]
Thanks Asanka, tried it on Chrome now and see what you mean, much better with the shading!

**Comment by AlbaPi** [comment]
Yes, Asanka! We think it's better if it could be restricted to unclaimed tasks! It may be confusing for the volunteers to see the task that have already been claimed. Thank you so much!!!!

**Comment by Wasala** [comment]
Working on this now.

**Comment by Wasala** [comment]
I've modified this feature according to your suggestions. Recently viewed tasks will now only show unclaimed tasks. As per @Paulina-Rosetta 's suggestion I have increased the gap between tasks. I have tested on Firefox and the shading appear fine.
