### ISSUE TITLE
User 9437 verified?

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1194]
Can you check if this user has been verified? http://trommons.org/9437/profile/
If not, maybe you can verify them manually?
Thanks!!

**Comment by alanbarrett** [comment]
Done.

**Comment by Paulina-Rosetta** [comment]
Ok , thanks Alan. For some reason I can't add this user as an organisation member. I'm getting an error to say they're not registsred. Any thoughts?
![add_user](https://cloud.githubusercontent.com/assets/4759025/8454216/9e438fbc-1ff3-11e5-8ef2-2e7f39ac86cc.png)

**Comment by alanbarrett** [comment]
After a bit of debugging... I worked out that you have spelled the e-mail wrong (or were told the wrong e-mail). It should be "imke.kaschke@specialolympis.de"... not "olympics"

I have now sucessfully added that user to the organisation.

    Alan.

**Comment by Paulina-Rosetta** [comment]
Turns out she misspelt the email when registering! Which explains why it wasn't verified. And she's got the wrong email on her user profile now, so what do we do? Just delete that account and get her to re-register? Sorry about the trouble!

**Comment by alanbarrett** [comment]
I issued the following and it should be good now...

UPDATE Users SET email='imke.kaschke@specialolympics.de' WHERE email='imke.kaschke@specialolympis.de';

    Alan.

**Comment by Paulina-Rosetta** [comment]
Thanks Alan!!
