### ISSUE TITLE
Order of projects on the organisation dashboard

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1195]
It would make our life - and possibly the organisations' lives - a lot easier if we changed the order in which projects are displayed on the dashboard. Right now they are in alphabetical order. I suggest displaying them by date - newest on top.
Would this be difficult to change?
Thanks!! @AlbaPi

**Comment by alanbarrett** [comment]
I should be able to do that... but it will have to wait 'till I get the
backend running on the test server... as I need that working as a test
environment in case we have any emergency.

    Alan.

**Comment by Wasala** [comment]
Need to include "order by" clause in : https://github.com/TheRosettaFoundation/SOLAS-Match/blob/develop/db/schema.sql#L2392 and subsequently following places needs to be changed:
API/DAO
https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/api/DataAccessObjects/ProjectDao.class.php#L101

API/Route
https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/api/v0/Orgs.php#L206

UI/DAO
https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/ui/DataAccessObjects/OrganisationDao.class.php#L51

UI/Route
https://github.com/TheRosettaFoundation/SOLAS-Match/blob/master/ui/RouteHandlers/OrgRouteHandler.class.php#L275

**Comment by alanbarrett** [comment]
I have this "done" and tested on the test server... but I need confirmation of what you want to be sure not to cause a problem.
In http://trommons.org/org/dashboard/
... I assume you still want all the tasks ordered alphabetically... however you want the projects within these organisations ordered by creation date, not by deadline.

Have I got that right, or not?

(of course, many users will only have one organisation.)

    Alan.

**Comment by Paulina-Rosetta** [comment]
Sorry Alan is this is confusing. On Dashboard, projects are ordered alphabetically under each organisation title. I'm proposing that they should be ordered by creation date, with the most recent projects on top. Am I making more sense now?
![dashboard](https://cloud.githubusercontent.com/assets/4759025/8721958/7af3f752-2bb7-11e5-8617-7e2cb31c4f60.png)

**Comment by alanbarrett** [comment]
I think so but the organisations will still be listed alphabetically (for
admins or those who have more than one organisation)... it is within each
organisation that you want the projects to be listed by creation date. Is
that correct?

    Alan.

**Comment by Paulina-Rosetta** [comment]
Yes, exactly!

**Comment by alanbarrett** [comment]
Done.
