### ISSUE TITLE
Accessing archived tasks

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1196]
Hi,

A volunteer has just asked to see a the proofread version of one of her trasnlations from last year. The project has since been archived. I'd like to give her a chance to look at the corrections though.
Before it was archived, the file was available for download here: http://trommons.org/org/29/task/3250/review

Any chance I could get access to this file?

**Comment by Wasala** [comment]
Sent an email with the file.
