### ISSUE TITLE
Broken project

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1200]
Not sure what happened here: http://trommons.org/project/3215/view/

Could you investigate?

Thanks!! @AlbaPi

**Comment by Wasala** [comment]
Currently there are no records of active tasks in the database for this project.
A task of this project, Task-9059  has already been archived and related files exist in the file system.

**Comment by alanbarrett** [comment]
Thanks Asanka! I have had a look at this also and can find nothing to explain any problems... but then you seem to indicate it is OK, so I will assume all is well.

**Comment by Paulina-Rosetta** [comment]
Thanks - all makes sense
