### ISSUE TITLE
Merge accounts?

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1201]
Is it possible to merge two accounts on Trommons i.e. add info from the one to another? A volunteer has two accounts, has been very active on one she'd like to keep and has completed one task on another. Could the task she completed be added to the more active account so it doesn't get lost (eg reference email)?

**Comment by alanbarrett** [comment]
I will look.

    Alan.

**Comment by alanbarrett** [comment]
If you tell me the two users (and which one is to have its info moved and which she wants to keep). I think I can do this.

    Alan.

**Comment by Paulina-Rosetta** [comment]
This is the account she wants removed: http://trommons.org/402/profile
This is the one she wants to keep: http://trommons.org/3327/profile

**Comment by alanbarrett** [comment]
I think I have done this. There did not seem to be any archived tasks, but I moved over one task: http://trommons.org/task/2814/id

    Alan.

**Comment by alanbarrett** [comment]
By the way, the old account is still there. I suppose she might still possibly get e-mails related to that.

    Alan.
