### ISSUE TITLE
Misleading description on review page

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1204]
There's a mistake on the review page which is where orgs download their translations. When a task they created/track is uploaded, they receive an email notification with a link to the review page (eg 'To download the the latest version of the file click here'.)
However, the link on the review page is incorrectly described as pointing to the source file: 'You can redownload the source file here.' This should say: 'You can download the output file here'.
This also affects the localised versions.
![download file](https://cloud.githubusercontent.com/assets/4759025/8983298/16a0c4c8-36c1-11e5-8f72-e16900697d51.png)

**Comment by alanbarrett** [comment]
I have done this for English and it is now on trommons.org. We will need translations for the other languages...

<string name="task_review_form_0">Du kannst die Ausgangsdatei <a href="%s">hier</a> nochmals herunterladen.</string>
<string name="task_review_form_0">Puedes volver a descargar el texto de origen <a href="%s">aquÃ­</a>.</string>
<string name="task_review_form_0">Puoi scaricare nuovamente il file sorgente <a href="%s">qui</a>.</string>

    Alan.

**Comment by Paulina-Rosetta** [comment]
Thank you very much Alan!! Is this enough or do you need the full strings?

DE: Du kannst die Datei hier herunterladen.
ES: Puedes volver a descargar el documento aquí­.
IT: Puoi scaricare il file qui.

**Comment by alanbarrett** [comment]
That should do.

    Alan.

**Comment by alanbarrett** [comment]
Done for all supported languages.

    Alan.
