### ISSUE TITLE
Download button not visible

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1210]
There seems to be a problem with this proofreading task: http://trommons.org/task/9880/id
The download button is not visible to me and the preview shows the original text rather than the translated text, which should be the source file for a proofreading task.

Any thoughts?

**Comment by alanbarrett** [comment]
I have spent about two hours trying to work out what happened. I cannot... also I cannot seem to be able to manually fix the problem. So I will have to give up. Sorry about that. If this occurs for other projects let me know.

I have the translated file, if that helps.

    Alan.

**Comment by Paulina-Rosetta** [comment]
Odd. I got it proofread and uploaded it no problem. I can download it ok too. I'll let you know if this comes up again. Thanks Alan!

**Comment by Paulina-Rosetta** [comment]
Here's another one: http://trommons.org/task/10008/view/
The project also displays a status of 25% when experience tells me it should be 50%.
Can you look at this one maybe?

**Comment by alanbarrett** [comment]
I have manually fixed this. It seems there originally was a translation
task, by mistake, I assume. It would have been deleted by someone... But
there seems to be a bug that leaves the proofreading waiting. I have not
yet researched or fixed that bug yet. But I will add it to my list and
hopefully get to it soonish.

In the mean time can you verify that the project is now OK?

    Alan.

**Comment by Paulina-Rosetta** [comment]
All good now, thanks Alan!!

**Comment by alanbarrett** [comment]
Finally... and it took quite a bit of work!... I have implemented a general solution for this. I have tested so all should be OK, but let me know if you see anything funny.

The solution involved...
If any WAITING_FOR_PREREQUISITES Task has a Prerequisite Task which is being deleted and it does not have any other non COMPLETE Prerequisites, set it to PENDING_CLAIM

    Alan.
