### ISSUE TITLE
Task Update emails

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1211]
To make Alba's life easier, I would suggest including a link to the relevant task in the Task Update emails. These emails are sent when a task deadline passes and since deadlines often need to be readjusted, a link in the email would be helpful. This is what they look like:

Paulina Abzieher, 
A task you are following on Trommons has passed its deadline. The task "Certificate for Climate Justice Ambassadors"  has passed its deadline. 
From, 
The Trommons Team 

See also #667

**Comment by alanbarrett** [comment]
I have now implemented this (added the link).

I have not done anything about the "See also".

    Alan.
