### ISSUE TITLE
Notifications e-mails

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1214]
This volunteer "clara@clarallamas.ie" is not receiving any notification e-mail. Any idea about which is the issue?

Thanks!

**Comment by alanbarrett** [comment]
There is no user with an e-mail of "clara@clarallamas.ie". There is a user with an e-mail of "clarallamas@me.com" and e-mails have been sent to that user.

I could change the e-mail address if that is the right thing to do.

    Alan.
