### ISSUE TITLE
Automatically registration

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1215]
I deteled twice this account from Trommons: mercedesvillegasbeguiristain@gmail.com

She is from an organisation and she is using another account, and it keeps registring on Trommons automatically. So weird!

**Comment by alanbarrett** [comment]
The account seems to have been created on 10th September, when did you delete it? Did it indicate success.

If you try again to delete, I can see if it has changed or been removed in any way.

    Alan.

**Comment by AlbaPi** [comment]
I deleted before the 10th. I've deleted her again now today. Let's wait what happens.

Thank you,
Alba

**Comment by alanbarrett** [comment]
I will (when I get time) have to look at how the Google Login/Registration
works. Maybe the software is designed to work this way. I will have to
check the code.

    Alan.

**Comment by Wasala** [comment]
If they already have an account in Trommons and if they are signed in to Google in their browser and visit Trommons,they will be automatically signed into Trommons.

**Comment by alanbarrett** [comment]
Alba was trying to delete the Trommons account for the user (it is using
their husband's e-mail). They wanted to use their own account in the future.

So if I understand you Asanka, the person should just not visit Trommons
when signed into their Husbands GMail account. Or if they do they should
sign out from Trommons? and then sign in to their own GMail account (if
they have one) and then go to Trommons and will be automatically logged in.

Asanka, is what I say correct?

Alba, would this work for the user or maybe they do not have their own
GMail account so they keep getting logged in using their husbands Gmail
account (which seems to recreate a Trommons account).

I am trying to get clear what is the technical issue and what exactly is
the user issue.

    Alan.

**Comment by Wasala** [comment]
@alanbarrett 

You are correct. Unless they haven't blocked 3rd party cookies in their browser, using the gmail account (currently) signed on,  they will get automatically signed into Trommons when visiting Trommons login page. This happens only if they have initially given Trommons the permission to use that gmail account. 

As you've mentioned, they should logout first from any other gmail accounts and then log into their own gmail account before visiting Trommon's login page.

Alternatively, you can ask the user to revoke access to Trommons for the former gmail account by logging into that account and visiting https://security.google.com/settings/security/permissions and removing Trommons from the list.

**Comment by alanbarrett** [comment]
Paulina, Alba,

Note the part from Asanka "you can ask the user to revoke access to Trommons for the former gmail account by logging into that account and visiting https://security.google.com/settings/security/permissions and removing Trommons from the list."

which should solve the translators problem.

    Alan.
