### ISSUE TITLE
Notification email sent to wrong volunteer

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1217]
No here's a curious one. I was contacted by a volunteer (http://trommons.org/9353/profile) to say she received the folllowing email:
 
Thank you for claiming a volunteering task on Trommons! You have one week to complete the "Translation" task for "témoignage Costa Rica (Urgent)" from Spanish into French. Please ensure to upload your file before the deadline passes. If you have any questions about the deadline, please contact info@trommons.org href="info@trommons.org">info@trommons.org
href="info@trommons.org">info@trommons.org href="info@trommons.org">info@trommons.org
href="info@trommons.org">info@trommons.org
From,
The Trommons Team 

This task (http://trommons.org/task/8873/view/) has been completed months ago by another volunteer: http://trommons.org/9115/profile/

I'm a little bit worried now.

**Comment by alanbarrett** [comment]
If that was before I made my fix last night then, I could understand that there had been incorrect parsing. However I still see errors today so it is not all solved... I am still looking at it.

    Alan.

**Comment by alanbarrett** [comment]
I did the change too late last night and while I copied down the new software to the backend. I forgot to compile it!!??

I have done that now and hopefully this will not reoccur... but I am abit worried also until this settles down.

I will close this as I think it should be fixed (hopefully).

    Alan.
