### ISSUE TITLE
Misleading description on review page

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1219]
One of the orgs has pointed out that they are asked to provie a review on the 'source file' on the review page. This is misleading, since they are reviewing translated or proofread files but not source files. I would suggest to change 'source file' to 'file' to avoid confusion. This will also need to be adressed in the localised versions.
![source file](https://cloud.githubusercontent.com/assets/4759025/10577582/56a46d62-7664-11e5-8e44-93908713ec85.png)

**Comment by alanbarrett** [comment]
Done for English.

Here are the source strings that will need to be updated for other languages...

<string name="task_review_form_2">Were there many mistakes in the file?</string>
<string name="task_review_form_3">How was the use of grammar in the file?</string>
<string name="task_review_form_4">Were there many spelling errors in the file?</string>
<string name="task_review_form_5">Were there any errors in consistency in the file?</string>

For simplicity I include the translated versions which might be easy to change...

<string name="task_review_form_2">Gab es in der Ausgangsdatei viele Fehler?</string>
<string name="task_review_form_3">Wie gut war die Grammatik in der Ausgangsdatei?</string>
<string name="task_review_form_4">Gab es in der Ausgangsdatei viele Rechtschreibfehler?</string>
<string name="task_review_form_5">Gab es in der Ausgangsdatei viele Inkonsistenzen?</string>

<string name="task_review_form_2">¿Tenía muchos errores el texto original?</string>
<string name="task_review_form_3">¿Tenía errores gramaticales el texto original?</string>
<string name="task_review_form_4">¿Tenía errores ortográficos el texto original?</string>
<string name="task_review_form_5">¿Tenía errores de coherencia el texto original?</string>

<string name="task_review_form_2">C'erano molti errori nel file sorgente?</string>
<string name="task_review_form_3">Che livello di grammatica c'era nel file sorgente?</string>
<string name="task_review_form_4">C'erano molti errori di ortografia nel file sorgente?</string>
<string name="task_review_form_5">C'erano errori di coerenza testuale nel file sorgente?</string>

    Alan.

**Comment by Paulina-Rosetta** [comment]
Thanks Alan! Here's German and Spanish. I'll get back to you about Italian.

Gab es in der Datei viele Fehler?
Wie gut war die Grammatik in der Datei?
Gab es in der Datei viele Rechtschreibfehler?
Gab es in der Datei viele Inkonsistenzen?

¿Tenía muchos errores el texto?
¿Tenía errores gramaticales el texto?
¿Tenía errores ortográficos el texto?
¿Tenía errores de coherencia el texto?

**Comment by alanbarrett** [comment]
I have updated German and Spanish on the server.

    Alan.

**Comment by Paulina-Rosetta** [comment]
Here's Italian:

C'erano molti errori nel file?
Che livello di grammatica c'era nel file?
C'erano molti errori di ortografia nel file?
C'erano errori di coerenza testuale nel file?

**Comment by alanbarrett** [comment]
Thanks... I think I did not get Italian for our other recent change???...

Modified English:
<string name="task_review_form_2">Were there many mistakes in the
file?</string>
<string name="task_review_form_3">How was the use of grammar in the
file?</string>
<string name="task_review_form_spelling">Spelling</string>
<string name="task_review_form_4">Were there many spelling errors in the
file?</string>

Unmodified Italian:
<string name="task_review_form_2">C'erano molti errori nel file
sorgente?</string>
<string name="task_review_form_3">Che livello di grammatica c'era nel file
sorgente?</string>
<string name="task_review_form_spelling">Ortografia</string>
<string name="task_review_form_4">C'erano molti errori di ortografia nel
file sorgente?</string>

    Alan.

2015-11-05 13:22 GMT+00:00 Paulina-Rosetta <notifications@github.com>:

**Comment by alanbarrett** [comment]
Ignore what I just wrote! I did not read the Italian!... I was getting my
issues mixed up (I thought it was for Twitter)... when I read the Italian,
I saw it was for the wording issue!

    Alan.

**Comment by alanbarrett** [comment]
Changes are now made for this on live server, I am closing.
