### ISSUE TITLE
Suspicious registrations

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1220]
In the last 24h we've had a number of new registrations from suspicious-looking email addresses such as
aseret@mailsdfsdf.com
uhofoldec@mailapso.com
erexia@mailasdkr.com
uzeyakx@asdfmail.net
irowiiyaj@fghmail.net

Could this be a problem?

**Comment by Paulina-Rosetta** [comment]
Something similar also occured on 26/10/15 and on 28/10/15

**Comment by alanbarrett** [comment]
It's not ideal... but people try out to see can they get something for free
or bypass security in some way... Our security is not great... but
hopefully it will stand up to amature/semi-professional attempts.

    Alan.

**Comment by alanbarrett** [comment]
I will close but let me know if the number surges. It could cause a loading issue for the backend because of the way it is written.

    Alan.
