### ISSUE TITLE
Changing word count after completion

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1241]
Alan,

This project has already been completed and the volunteer has complained that the word count was incorrect. She would like it changed so it appears correctly on her reference. Is this possible?

Here's the project: http://trommons.org/task/17665/view/

The actual word count was 1120 words.

**Comment by Wasala** [comment]
Did you try: http://trommons.org/project/5280/alter/

**Comment by alanbarrett** [comment]
I don't think changing the Project word count (although probably good for consistency) will change the Task word count. I have now done this via SQL.

    Alan.

**Comment by Paulina-Rosetta** [comment]
Thank you Asanka and Alan!
