### ISSUE TITLE
Desegmentation bug

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1243]
When I go to upload the files for this desegmentation (https://trommons.org/task/18533/desegmentation/) I get the following error:
 
Slim Application Error
Message:Undefined variable: preReqTasks
Loc: /repo/SOLAS-Match/ui/RouteHandlers/TaskRouteHandler.class.php
Line: 928
Code: 8

Trace: 

0 /repo/SOLAS-Match/ui/RouteHandlers/TaskRouteHandler.class.php(928): Slim\Slim::handleErrors(8, 'Undefined varia...', '/repo/SOLAS-Mat...', 928, Array) 
1 [internal function]: SolasMatch\UI\RouteHandlers\TaskRouteHandler->desegmentationTask('18533') 
2 /repo/SOLAS-Match/ui/vendor/slim/slim/Slim/Route.php(441): call_user_func_array(Array, Array) 
3 /repo/SOLAS-Match/ui/vendor/slim/slim/Slim/Slim.php(1314): Slim\Route->dispatch() 
4 /repo/SOLAS-Match/ui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() 
5 /repo/SOLAS-Match/ui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() 
6 /repo/SOLAS-Match/ui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call() 
7 /repo/SOLAS-Match/ui/vendor/slim/slim/Slim/Slim.php(1261): Slim\Middleware\SessionCookie->call() 
8 /repo/SOLAS-Match/index.php(195): Slim\Slim->run() 
9 {main}

**Comment by alanbarrett** [comment]
Fixed by 557c3655c13bc50066da4265d01a912ecd3d9bf6

Someone had forgotten to initialise a variable. PHP used to let you away with that. This crash only occurs if the task has no prerequisites.

I have a vague memory of noticing this code before but assumed that whoever wrote it knew what they were doing.

    Alan.
