### ISSUE TITLE
Track Task Gives wrong Message

### ISSUE THREAD

**Issue by alanbarrett** [TheRosettaFoundation/SOLAS-Match#1247]
When I Track a Task in e.g. https://trommons.org/task/18981/view/
it works but gives the wrong message (it says: You are no longer tracking this task and will receive no further emails.)

Likewise un-tracking gives the wrong message (You are now tracking this task and will receive email notifications when its status changes.).

@Paulina-Rosetta have you noticed this? Am I missing something?

```
Alan.
```

**Comment by Paulina-Rosetta** [comment]
I had never noticed this! Probably because I usually track projects rather than tasks. Also, it seems to work fine when I try to un/track the task on the Project page rather than the Task page.

**Comment by alanbarrett** [comment]
OK I will fix, good to know it just happens on task page.

    Alan.

**Comment by alanbarrett** [comment]
@Paulina-Rosetta 
Fixed by commit 3786cf975ab741c14d901a810442e5c6d2128bdf

    Alan.
