### ISSUE TITLE
Completed task needs to be reassigned

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1250]
This task is 'Complete' but the volunteer uploaded an incomplete translation: https://trommons.org/task/18315/view/

A complete translation has now been sent to us by a different volunteer. We want to revoke the task and reassign it to this volunteer so they can upload their file: https://trommons.org/9453/profile/

**Comment by alanbarrett** [comment]
It is dangerous for me to do exactly what you want. But I could upload the completed file if you send to me and change the user who has claimed the task. So then everything should be more or less OK (I hope).

One stange thing though is that it seems as if https://trommons.org/15613/profile/ has unclaimed the task, which should have made the task available again, but maybe that was done too late??? (not sure if that is possible.)

    Alan.

**Comment by Paulina-Rosetta** [comment]
I'll send the file now, can't attach it here cause it's a .doc. Thanks Alan!!

**Comment by alanbarrett** [comment]
Uploaded file
sudo cp -p ~/CRPD-GC-4.doc /repo/SOLAS-Match/backup/uploads/proj-5482/task-18315/v-1/CRPD-GC-4.doc
sudo chown www-data:www-data /repo/SOLAS-Match/backup/uploads/proj-5482/task-18315/v-1/CRPD-GC-4.doc
sudo chmod 644 /repo/SOLAS-Match/backup/uploads/proj-5482/task-18315/v-1/CRPD-GC-4.doc

UPDATE TaskFileVersions SET user_id=9453 WHERE id=34538;
UPDATE TaskClaims SET user_id=9453 WHERE id=16562;

    Alan.
