### ISSUE TITLE
Cannot change deadlines on 'In progress' tasks

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1256]
While this might sound like it shouldn't be possible, it is usually possible, but not in this case.

We added new languages to an old project yesterday: https://trommons.org/project/5622/view/
This involved adding two segmentation tasks. When the segments for these were uploaded, they (the segments = translation tasks) took their deadlines from the old project deadline which was 29 Nov. I have since changed the project deadline to 31 Dec.

So the translation tasks that were created had a deadline of 25 Nov, which needed to be changed. By changing the project deadline, the deadline on all UNCLAIMED tasks was automatically updated to 27 Dec. However, a substantial number of tasks have already been claimed, and in order to avoid complaints and confusion, I have tried to update the deadlines on these claimed tasks manually. The system usually allows me to do this. While some details cannot be changed on claimed (In progress) tasks, the deadline can usually be changed.

When I try to change these deadlines, I get the following error:

A deadlock has occured, please check your task prerequisites.

**Comment by alanbarrett** [comment]
"public function parseAndBuild($graphArray)" is returning false.

I may not get to sorting this out straight away I do not understand this part of the code and as I have committed to help a Nephew (and separately a Niece) with Maths and other Engineering studies.

Maybe @aquilax will get a chance over the weekend, but if not, I will look at it.

    Alan.

**Comment by alanbarrett** [comment]
I can reproduce and have started to look at this. I have dumped the "$graphArray" in the log.

    Alan.

**Comment by aquilax** [comment]
@alanbarrett sorry, saw this just now.

**Comment by alanbarrett** [comment]
That is OK, I have started to look at it.

    Alan.

**Comment by alanbarrett** [comment]
At last..
The Template has checkboxes disabled when a task has been Claimed, so they will never be successfully sent to server.
So the server ends up incorrectly with a NULL for the prerequisites for the current task being edited.
This causes the "deadlock" error to be displayed incorrectly.
So I have changed the code to not take the new prerequisites from the browser template when
a task is Claimed or Complete (but rather keep the old ones).

See commit dbfb206dcf122222fdebd45630aa23533bcdb926

However it does not seem to be possible to set the deadline backwards in time...
But if you tell me the Tasks that you want to change the deadline for, I will do it in the database manually, if you give me the date
e.g. 2016-12-25 23:00:00

    Alan.
