### ISSUE TITLE
Setting to unpublish task when creating a new project doesn't work

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1264]
On the Project Create page, there is a checkbox (Publish Tasks) that can be unticked to make sure newly created tasks don't immediately get published. This is sometimes important for privacy reasons.

When creating six new projects yesterday, I unticked this box each time, but all tasks ended up published. I had no problem unpublishing them manually afterwards.

**Comment by alanbarrett** [comment]
I cannot replicate this on the test server. On Monday can we do a test on trommons.org and I can check the database.

    Alan.

**Comment by alanbarrett** [comment]
@Paulina-Rosetta Are you free to do a test now?... we could Skype. Or maybe also at 1:45pm or else we can leave for a day or two if you are busy.

    Alan.

**Comment by alanbarrett** [comment]
@Paulina-Rosetta can you do another test of an unpublished project create whenever you can. I will not be around until the afternoon to look at the results. Just be sure to check it is really still published before you remove from task stream or whatever you do (did you do that to today's one yet?).

I have added error logging which should tell me more.

    Alan.

**Comment by Paulina-Rosetta** [comment]
I created a new test project now. It was definitely still published but I subsequently unpublished both tasks manually: https://trommons.org/project/6110/view/
I have deleted the other two test projects I created yesterday.

**Comment by alanbarrett** [comment]
This is actually a backend issue: https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/issues/48

    Alan.
