### ISSUE TITLE
Org member cannot reset password

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1265]
I got an email from an org member who cannot reset her password. This is her address: montsem@fundacionpineda.org

She has a profile on Trommons (https://trommons.org/15969/profile/) and is a member of this organisation: https://trommons.org/org/330/profile/

When her email is put into the Reset password box the following error message appears:
**Error! Failed to request password reset, are you sure you entered your email address correctly?**

I've also tried to verfied her email address manually in case it was never properly verified. When I put her email into the verficiation box on the Admin page, I get the following message: 
**User not found, the provided email address does not correspond to an account on our system.**

All very confusing.

**Comment by alanbarrett** [comment]
Her email in the system is: montsem@fundaciopineda.org
not montsem@fundacionpineda.org (missing "n")... will I change it?

    Alan.

**Comment by Paulina-Rosetta** [comment]
Yes please, sorry for overlooking!

**Comment by alanbarrett** [comment]
I have changed her email to montsem@fundacionpineda.org
(but not reset her password).

    Alan.
