### ISSUE TITLE
Badge Awarded notification email needs update

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#1268]
I just noticed that the Badge Awarded notification email could do with an update. It reads:

Paulina Abzieher, 
Congratulations! You’ve been awarded the badge on Trommons. 
Sincerely,
The Trommons Team 

As a minimum change, I would suggest:

Paulina Abzieher, 
Congratulations! You’ve been awarded **a** badge on Trommons. 
Sincerely,
The Trommons Team 

We could also think about adding the organisation name, such as:

Paulina Abzieher, 
Congratulations! You’ve been awarded **a** badge on Trommons **by [ORG NAME]** 
Sincerely,
The Trommons Team

**Comment by alanbarrett** [comment]
Resolved: https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/issues/49
