### ISSUE TITLE
Limit some Tasks to "Qualified" Translators

### ISSUE THREAD

**Issue by alanbarrett** [TheRosettaFoundation/SOLAS-Match#1272]
We already have a system for this, but it is all or none for an organisation... Once there is one "Qualified" badge for an organisation, tasks for that organisation are only shown to those with that badge.

@Paulina-Rosetta and @stefania91 want to make this more fine grained. So I would add a flag (or a text attribute e.g. "Qualified") to each task to indicate it needs a qualified translator. I had avoided doing this the last time.

The UI for Project Create, Task Create and Task Edit would be changed to have a checkbox to indicate that it is only for "Qualified" volunteers.

Questions...

1) Is this OK?
2) Should there be more than one type of qualification? in which case I would use a text attribute string rather than a checkbox? This would allow different types of project as well as different qualifications for example for translators or proofreaders.
3) I could just show the UI for those Organisations that have a "Qualified" Badge (so they are already using the existing qualified system). This would stop organisations becoming too selective for translators unless there was a clear need agreed by us?
4) Would the default be checked or unchecked (for Organisations that have the Qualified badge already)?

We should discuss tomorrow.

    Alan.

**Comment by Paulina-Rosetta** [comment]
Amazing - thanks Alan. We had a quick chat about this and have come up with the following:

1) Yes, definitely works for us
2) One type of qualification and a checkbox works for us
3) Yes, for now it only makes sense to provide this option to orgs with the Qualified badge as we need to arrange for testing or the signing of agreements  with them before restricting projects
4) The default would be checked for orgs with the Qualified badge

**Comment by alanbarrett** [comment]
@Paulina-Rosetta , @stefania91 

Here is the wording for the Project Create page...
<string name="restrict_tasks">Restrict Tasks</string>
<string name="restrict_tasks_long">If checked, tasks will only be shown to volunteers with the "Qualified" badge for your organisation.</string>

Here is the wording for the Task Create/Edit page...
<string name="restrict_task">Restrict Task</string>
<string name="restrict_task_long">If checked, task will only be shown to volunteers with the "Qualified" badge for your organisation.</string>

Please can you comment on the suitability of the wording. When I have check if these fit on the page, I will ask for translations.

    Alan.

**Comment by Paulina-Rosetta** [comment]
Thanks Alan. I think this will suffice:
**If checked, tasks will only be shown to qualified volunteers.**

The reason for the change is that most orgs don't create the Qualified badge themselves - we create it for them - so they may be confused by the wording.

Stefania is out today so maybe let's wait till tomorrow to decide.

**Comment by alanbarrett** [comment]
@Paulina-Rosetta 
That will also fit better. Can you organise translations (for the 4 strings) when you have finalised?

    Alan.

**Comment by alanbarrett** [comment]
Fixed by commit d292856675bb348a02fce913932def2f10e73cba
(Translations to follow)

Also fixed Published bug for when uploading/creating follow on tasks  for segmentation task.

    Alan.

**Comment by stefania91** [comment]
This is the Italian wording. I tried and keep it short, but it's still a bit longer than the English. I can try and cut off something if you need me to!

Accesso limitato
Selezionare per rendere questo contenuto visibile solo a chi possiede un riconoscimento.

**Comment by alanbarrett** [comment]
@stefania91 
Thanks, is that for the singular or plural (or both?)...

"Restrict Tasks"
"If checked, tasks will only be shown to volunteers with the "Qualified" badge for your organisation."
"Restrict Task"
"If checked, task will only be shown to volunteers with the "Qualified" badge for your organisation."

    Alan.

**Comment by stefania91** [comment]
I made it generic, I just said "this content" so that we can use it for both projects and tasks. Do you think it's clear enough?

**Comment by alanbarrett** [comment]
OK great, It will fit no problem.

    Alan.

**Comment by Paulina-Rosetta** [comment]
Sorry my mistake. I thought we were going with this for both:
"Restrict Tasks"
"If checked, tasks will only be shown to qualified volunteers."

I didnt notice the difference when I asked Stefania for the Italian

**Comment by Paulina-Rosetta** [comment]
GERMAN:

"Restrict Tasks"
"If checked, tasks will only be shown to qualified volunteers."
"Beschränkte Aufgaben"
"Wenn diese Option ausgewählt ist, sind die Aufgaben nur für qualifizierte Freiwillige sichtbar."

"Restrict Task"
"If checked, task will only be shown to qualified volunteers."
"Beschränkte Aufgabe"
"Wenn diese Option ausgewählt ist, ist die Aufgabe nur für qualifizierte Freiwillige sichtbar."

**Comment by Paulina-Rosetta** [comment]
SPANISH:

"If checked, tasks will only be shown to qualified volunteers."
Singular: Si marcas la casilla, la tarea solo se mostrará a los voluntarios aptos para completarla.
Plural: Si marcas la casilla, las tareas solo se mostrarán a los voluntarios aptos para completarlas.

**Comment by alanbarrett** [comment]
But for Spanish I also need

"Restrict Task"
and
"Restrict Tasks"

    Alan.

**Comment by Paulina-Rosetta** [comment]
Limitar tarea

Limitar tareas

**Comment by alanbarrett** [comment]
Translations are now in and look OK.

    Alan.
