### ISSUE TITLE
Cannot update profile details on Firefox 31.0

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match#999]
![profile](https://cloud.githubusercontent.com/assets/4759025/4117666/71ede51c-3295-11e4-871d-0351fbf51c9b.png)
Tried to update my profile, the languges never appear and I get an error message - see screenshot. Works fine on Chrome.

**Comment by Paulina-Rosetta** [comment]
Any news on this?

**Comment by Wasala** [comment]
Unfortunately both of our Dart experts are gone ; @TheIceMageX50 and @spaceindaver 
There is a considerable learning curve for me to fix these on my own unless you can recruit a Dart expert pretty soon!

**Comment by TheIceMageX50** [comment]
I would like to help somewhat actively but unfortunately I have FYP work among other things to take care of. :[
However I just realised now there is something from a while back I wanted to share with you. You may recall how a while back I mentioned I would post online to ask for guidance for helping to update the system's Polymer and such...well I did that [here](https://groups.google.com/a/dartlang.org/forum/#!topic/web/joKTglh6ftI). There wasn't a huge amount of discussion as you'll see but one thing that seems like it could be a decent starting point is the release notes page that "sigmund" mentioned there.

**Comment by Wasala** [comment]
Hey @TheIceMageX50 , you must give priority for your thesis!! and thank you very much for this info.. I will try to look into this but before that #1119 is the number one priority in my end.

**Comment by Paulina-Rosetta** [comment]
@TheIceMageX50 Good luck with your thesis. And thanks so much for helping out!!

**Comment by TheIceMageX50** [comment]
I guess since it's my FYP it's really more practical work (programming) than anything like a thesis, though I will inevitably also need to submit an "FYP report" as part of it as well. But thanks for the good wishes everyone. :)

**Comment by Wasala** [comment]
@alanbarrett I guess we can mark this as resolved?

**Comment by alanbarrett** [comment]
Fixed by new JavaScript code.
